### PR TITLE
Added screensize check

### PR DESCRIPTION
**Pull request by SabatinoMasala**
Added a check to get the device by screen size, to group iPhones and iPods together.

### CODE REVIEW

**Comment by SabatinoMasala** [comment]
iOS 7 support should be on a separate branch, since including the availability check in the framework will cause warnings when using a deployment target of iOS 8 or higher.

**Comment by FabrizioBrancati** [comment]
But I want to be compatible with iOS 7, and if I'll create a new branch I'll have to keep it updated with the master branch.
I don't think that 3 warnings will be a problem, and the build now fails because the deployment target is iOS 7.

If you use it as a Framework no warnings will be shown.

**Comment by FabrizioBrancati** [comment]
The other things are interesting, if you add again support to iOS 7 I'll merge it!

**Comment by SabatinoMasala** [comment]
There we go, that should've done it.

**Comment by FabrizioBrancati** [comment]
Thanks! :+1:

**Pull request merged**
