### PR TITLE
Update NSAttributedString+Extensions.swift

### PR DESCRIPTION
**Pull request by ghost**
WIP - Will Finish

### CODE REVIEW

**Comment by FabrizioBrancati** [comment]
Thanks for these improvements! 👍

**Comment by ghost** [comment]
You know what? Maybe there should be a new API instead of all the renaming. 

    attrString.applying {
        $0.backgroundColor = ...
    }

**Comment by FabrizioBrancati** [comment]
It would be great! We will have something like [SwiftRichString](https://github.com/malcommac/SwiftRichString), but lighter.

**Comment by ghost** [comment]
I have closed this and will clone to start working on the idea.

**Comment by FabrizioBrancati** [comment]
Great! 👍

**Pull request closed without merging**
